/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dp_cecile_biomusic_MidiDriver */

#ifndef _Included_com_dp_cecile_biomusic_MidiDriver
#define _Included_com_dp_cecile_biomusic_MidiDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dp_cecile_biomusic_MidiDriver
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dp_cecile_biomusic_MidiDriver_init
  (JNIEnv *, jobject);

/*
 * Class:     com_dp_cecile_biomusic_MidiDriver
 * Method:    config
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_dp_cecile_biomusic_MidiDriver_config
  (JNIEnv *, jobject);

/*
 * Class:     com_dp_cecile_biomusic_MidiDriver
 * Method:    write
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dp_cecile_biomusic_MidiDriver_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_dp_cecile_biomusic_MidiDriver
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dp_cecile_biomusic_MidiDriver_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
